# This workflow will install Python dependencies, run tests, and lint with a single version of Python
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

# This section defines the event triggers (when the workflow should run)
on:
  push:
    branches: [ "main" ]  # Trigger on push to the 'main' branch
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests to the 'main' branch

permissions:
  contents: read  # Specifies the minimum permission required to read the repository's contents

jobs:
  build:
    # This defines the virtual machine environment to run the job
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Checkout the repository's code so the job can access it

    # Set up Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"  # Specify the Python version to use

    # Install Python dependencies and linting/testing tools
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Ensure pip is the latest version
        pip install flake8 pytest  # Install flake8 (for linting) and pytest (for testing)
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # If a requirements file exists, install dependencies

    # Run tests with pytest
    - name: Test with pytest --pylint
      run: |
        pytest  # Runs the tests using pytest
